### ISSUE TITLE
Does it prohibit gradio webui?

### ISSUE THREAD

**Issue by rsxdalv** [oneir0mancer/stable-diffusion-diffusers-colab-ui#1]
Could you please provide a reference to that statement.

**Comment by oneir0mancer** [comment]
Here are some links: [1](https://twitter.com/thechrisperry/status/1649189902079381505) [2](https://www.reddit.com/r/StableDiffusion/comments/12t8tc7/comment/jh2yhaz/) [3](https://github.com/googlecolab/colabtools/issues/3591). In short, if you use free Colab account, any mention of "stable-diffusion-webui" in code will trigger a warning. 

I'm guessing it was just a quick hack to lower workload until they find an actual way to stop gradio servers that run on colab.

**Comment by rsxdalv** [comment]
Oh, not going to lie I find I very arbitrary. Nevertheless it's reasonable. I'm just guessing that if you succeeded in making a very successful google Collab for stable diffusion you would meet the same fate, wouldn't you?
