### ISSUE TITLE
Img2Img Refiner doesn't load

### ISSUE THREAD

**Issue by ghost** [oneir0mancer/stable-diffusion-diffusers-colab-ui#14]
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:655: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(
Could not locate the None.py inside None.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    285     try:
--> 286         response.raise_for_status()
    287     except HTTPError as e:

**Comment by oneir0mancer** [comment]
I broke something when adding Clip Skip support. Should be fixed now.
