### ISSUE TITLE
Img2Img doesn't save an image

### ISSUE THREAD

**Issue by ghost** [oneir0mancer/stable-diffusion-diffusers-colab-ui#15]
[/content/StableDiffusionUi/ColabUI/BaseUI.py](https://localhost:8080/#) in save_image_with_metadata(self, image, path, additional_data)
     43     def save_image_with_metadata(self, image, path, additional_data = ""):
     44         meta = PngInfo()
---> 45         meta.add_text("Data", self._metadata + additional_data)
     46         image.save(path, pnginfo=meta)
     47 

AttributeError: 'DiffusionPipelineUI' object has no attribute '_metadata'

**Comment by oneir0mancer** [comment]
Should be fixed now.
