### ISSUE TITLE
Running a cell results in "guidance_rescale" error

### ISSUE THREAD

**Issue by victorurizar** [oneir0mancer/stable-diffusion-diffusers-colab-ui#16]
I have a problem when running the cell called "Run this cell to generate images". When it comes to reaching that cell, it gives me the following error:

![02-07-2024 02-19-23 _Screenshot_10d469b7-fe70-4108-b908-ed33d3694a7a](https://github.com/oneir0mancer/stable-diffusion-diffusers-colab-ui/assets/112921530/ad07bc60-5c12-4e53-9286-5cad6ef36667)

I have to say that the notebook worked for me the first time, but when I deleted the environment and did it again from scratch for the second time, it started giving me this error.

And yes, I have disconnected and deleted the environment.
I have also verified if the notebook link is the same as the one in this Github and it is the same, without changes or anything.

**Comment by oneir0mancer** [comment]
My bad, I made an update but tested it only on SDXL pipeline. Error should be fixed now.

**Comment by victorurizar** [comment]
### ****Perfect, it works now!. Thank you!****

![02-07-2024 13-54-48 _Screenshot_174aaaa4-ec01-49ef-8cd9-7e81bb7140df](https://github.com/oneir0mancer/stable-diffusion-diffusers-colab-ui/assets/112921530/4c726dfd-2d47-4a1d-b469-35d0f192f58a)
