### ISSUE TITLE
Running the cell “ Render model choice UI” returns an error

### ISSUE THREAD

**Issue by GangreI** [oneir0mancer/stable-diffusion-diffusers-colab-ui#17]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
   1566         try:
-> 1567             return importlib.import_module("." + module_name, self.__name__)
   1568         except Exception as e:

58 frames
RuntimeError: operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
RuntimeError: Failed to import transformers.models.auto.image_processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
RuntimeError: Failed to import diffusers.loaders.single_file_model because of the following error (look up to see its traceback):
Failed to import transformers.models.auto.image_processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/diffusers/utils/import_utils.py](https://localhost:8080/#) in _get_module(self, module_name)
    808             return importlib.import_module("." + module_name, self.__name__)
    809         except Exception as e:
--> 810             raise RuntimeError(
    811                 f"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its"
    812                 f" traceback):\n{e}"

RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.single_file_model because of the following error (look up to see its traceback):
Failed to import transformers.models.auto.image_processing_auto because of the following error (look up to see its traceback):
operator torchvision::nms does not exist

**Comment by oneir0mancer** [comment]
I locked package version, so this should be fixed now. Things tend to break when there are updates to packages.
