### ISSUE TITLE
support for civitai

### ISSUE THREAD

**Issue by phineas-pta** [oneir0mancer/stable-diffusion-diffusers-colab-ui#2]
url from civitai dont work

in fact we need additional conversion to diffusers with these scripts
- https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py
- https://github.com/huggingface/diffusers/blob/main/scripts/convert_lora_safetensor_to_diffusers.py

**Comment by oneir0mancer** [comment]
Diffusers can handle those models out of the box now, so there's really no need for the scripts. (Besides, they are already in colab at the bottom.)

You can't load models from civitai directly, but you can download them first with something like:
```
!wget https://civitai.com/api/download/models/XXXXXX --content-disposition
```
and then put path to the model into the UI and check `✅ A1111 format`. The model will load just fine.

Same deal with loras really, just download and use
```
pipe.load_lora_weights("path/to/folder", weight_name="lora_filename.safetensors")
```

**Comment by phineas-pta** [comment]
oh i thought it's auto handled when i paste a link, i can send a PR if u want

**Comment by oneir0mancer** [comment]
Sure.
