### ISSUE TITLE
Load VAE from single file.

### ISSUE THREAD

**Issue by ihbdesu** [oneir0mancer/stable-diffusion-diffusers-colab-ui#5]
When trying to load vae, it seems to require a config file, but not all of them have configs. 
For example https://huggingface.co/stabilityai/sd-vae-ft-mse-original

**Comment by oneir0mancer** [comment]
You can try loading vae [like this](https://huggingface.co/docs/diffusers/v0.25.0/en/api/models/autoencoderkl#loading-from-the-original-format):
```
colab.pipe.vae = AutoencoderKL.from_single_file("path/to/file").to("cuda")
```

Right now I'm reworking UI a little, an when I'm done it will support loading vae from single file.
