### ISSUE TITLE
TypeError: ColabWrapper.generate() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by ghost** [oneir0mancer/stable-diffusion-diffusers-colab-ui#9]
TypeError                                 Traceback (most recent call last)
[<ipython-input-15-6c9877edbdad>](https://localhost:8080/#) in <cell line: 2>()
      1 #@title <font color='red'>Run</font> this cell to generate images
----> 2 colab.generate(save_images, display_previewes)

TypeError: ColabWrapper.generate() takes from 1 to 2 positional arguments but 3 were given

**Comment by oneir0mancer** [comment]
Seems like you are using an outdated colab notebook. 
I've checked now, and this cell is correct on my end:
```python
#@title <font color='red'>Run</font> this cell to generate images
colab.generate(display_previewes=display_previewes)
```
